/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/apikey": {
    get: operations["HeadscaleService_ListApiKeys"];
    post: operations["HeadscaleService_CreateApiKey"];
  };
  "/api/v1/apikey/expire": {
    post: operations["HeadscaleService_ExpireApiKey"];
  };
  "/api/v1/apikey/{prefix}": {
    delete: operations["HeadscaleService_DeleteApiKey"];
  };
  "/api/v1/debug/node": {
    post: operations["HeadscaleService_DebugCreateNode"];
  };
  "/api/v1/health": {
    get: operations["HeadscaleService_Health"];
  };
  "/api/v1/node": {
    get: operations["HeadscaleService_ListNodes"];
  };
  "/api/v1/node/backfillips": {
    post: operations["HeadscaleService_BackfillNodeIPs"];
  };
  "/api/v1/node/register": {
    post: operations["HeadscaleService_RegisterNode"];
  };
  "/api/v1/node/{nodeId}": {
    get: operations["HeadscaleService_GetNode"];
    delete: operations["HeadscaleService_DeleteNode"];
  };
  "/api/v1/node/{nodeId}/approve_routes": {
    post: operations["HeadscaleService_SetApprovedRoutes"];
  };
  "/api/v1/node/{nodeId}/expire": {
    post: operations["HeadscaleService_ExpireNode"];
  };
  "/api/v1/node/{nodeId}/rename/{newName}": {
    post: operations["HeadscaleService_RenameNode"];
  };
  "/api/v1/node/{nodeId}/tags": {
    post: operations["HeadscaleService_SetTags"];
  };
  "/api/v1/policy": {
    get: operations["HeadscaleService_GetPolicy"];
    put: operations["HeadscaleService_SetPolicy"];
  };
  "/api/v1/preauthkey": {
    get: operations["HeadscaleService_ListPreAuthKeys"];
    post: operations["HeadscaleService_CreatePreAuthKey"];
    delete: operations["HeadscaleService_DeletePreAuthKey"];
  };
  "/api/v1/preauthkey/expire": {
    post: operations["HeadscaleService_ExpirePreAuthKey"];
  };
  "/api/v1/user": {
    get: operations["HeadscaleService_ListUsers"];
    post: operations["HeadscaleService_CreateUser"];
  };
  "/api/v1/user/{id}": {
    delete: operations["HeadscaleService_DeleteUser"];
  };
  "/api/v1/user/{oldId}/rename/{newName}": {
    post: operations["HeadscaleService_RenameUser"];
  };
}

export interface definitions {
  HeadscaleServiceSetApprovedRoutesBody: {
    routes?: string[];
  };
  HeadscaleServiceSetTagsBody: {
    tags?: string[];
  };
  protobufAny: {
    "@type"?: string;
  } & { [key: string]: unknown };
  rpcStatus: {
    /** Format: int32 */
    code?: number;
    message?: string;
    details?: definitions["protobufAny"][];
  };
  v1ApiKey: {
    /** Format: uint64 */
    id?: string;
    prefix?: string;
    /** Format: date-time */
    expiration?: string;
    /** Format: date-time */
    createdAt?: string;
    /** Format: date-time */
    lastSeen?: string;
  };
  v1BackfillNodeIPsResponse: {
    changes?: string[];
  };
  v1CreateApiKeyRequest: {
    /** Format: date-time */
    expiration?: string;
  };
  v1CreateApiKeyResponse: {
    apiKey?: string;
  };
  v1CreatePreAuthKeyRequest: {
    /** Format: uint64 */
    user?: string;
    reusable?: boolean;
    ephemeral?: boolean;
    /** Format: date-time */
    expiration?: string;
    aclTags?: string[];
  };
  v1CreatePreAuthKeyResponse: {
    preAuthKey?: definitions["v1PreAuthKey"];
  };
  v1CreateUserRequest: {
    name?: string;
    displayName?: string;
    email?: string;
    pictureUrl?: string;
  };
  v1CreateUserResponse: {
    user?: definitions["v1User"];
  };
  v1DebugCreateNodeRequest: {
    user?: string;
    key?: string;
    name?: string;
    routes?: string[];
  };
  v1DebugCreateNodeResponse: {
    node?: definitions["v1Node"];
  };
  v1DeleteApiKeyResponse: { [key: string]: unknown };
  v1DeleteNodeResponse: { [key: string]: unknown };
  v1DeletePreAuthKeyResponse: { [key: string]: unknown };
  v1DeleteUserResponse: { [key: string]: unknown };
  v1ExpireApiKeyRequest: {
    prefix?: string;
  };
  v1ExpireApiKeyResponse: { [key: string]: unknown };
  v1ExpireNodeResponse: {
    node?: definitions["v1Node"];
  };
  v1ExpirePreAuthKeyRequest: {
    /** Format: uint64 */
    user?: string;
    key?: string;
  };
  v1ExpirePreAuthKeyResponse: { [key: string]: unknown };
  v1GetNodeResponse: {
    node?: definitions["v1Node"];
  };
  v1GetPolicyResponse: {
    policy?: string;
    /** Format: date-time */
    updatedAt?: string;
  };
  v1HealthResponse: {
    databaseConnectivity?: boolean;
  };
  v1ListApiKeysResponse: {
    apiKeys?: definitions["v1ApiKey"][];
  };
  v1ListNodesResponse: {
    nodes?: definitions["v1Node"][];
  };
  v1ListPreAuthKeysResponse: {
    preAuthKeys?: definitions["v1PreAuthKey"][];
  };
  v1ListUsersResponse: {
    users?: definitions["v1User"][];
  };
  v1Node: {
    /** Format: uint64 */
    id?: string;
    machineKey?: string;
    nodeKey?: string;
    discoKey?: string;
    ipAddresses?: string[];
    name?: string;
    user?: definitions["v1User"];
    /** Format: date-time */
    lastSeen?: string;
    /** Format: date-time */
    expiry?: string;
    preAuthKey?: definitions["v1PreAuthKey"];
    /** Format: date-time */
    createdAt?: string;
    registerMethod?: definitions["v1RegisterMethod"];
    forcedTags?: string[];
    invalidTags?: string[];
    validTags?: string[];
    givenName?: string;
    online?: boolean;
    approvedRoutes?: string[];
    availableRoutes?: string[];
    subnetRoutes?: string[];
  };
  v1PreAuthKey: {
    user?: definitions["v1User"];
    /** Format: uint64 */
    id?: string;
    key?: string;
    reusable?: boolean;
    ephemeral?: boolean;
    used?: boolean;
    /** Format: date-time */
    expiration?: string;
    /** Format: date-time */
    createdAt?: string;
    aclTags?: string[];
  };
  /**
   * @default REGISTER_METHOD_UNSPECIFIED
   * @enum {string}
   */
  v1RegisterMethod:
    | "REGISTER_METHOD_UNSPECIFIED"
    | "REGISTER_METHOD_AUTH_KEY"
    | "REGISTER_METHOD_CLI"
    | "REGISTER_METHOD_OIDC";
  v1RegisterNodeResponse: {
    node?: definitions["v1Node"];
  };
  v1RenameNodeResponse: {
    node?: definitions["v1Node"];
  };
  v1RenameUserResponse: {
    user?: definitions["v1User"];
  };
  v1SetApprovedRoutesResponse: {
    node?: definitions["v1Node"];
  };
  v1SetPolicyRequest: {
    policy?: string;
  };
  v1SetPolicyResponse: {
    policy?: string;
    /** Format: date-time */
    updatedAt?: string;
  };
  v1SetTagsResponse: {
    node?: definitions["v1Node"];
  };
  v1User: {
    /** Format: uint64 */
    id?: string;
    name?: string;
    /** Format: date-time */
    createdAt?: string;
    displayName?: string;
    email?: string;
    providerId?: string;
    provider?: string;
    profilePicUrl?: string;
  };
}

export interface operations {
  HeadscaleService_ListApiKeys: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ListApiKeysResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_CreateApiKey: {
    parameters: {
      body: {
        body: definitions["v1CreateApiKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1CreateApiKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ExpireApiKey: {
    parameters: {
      body: {
        body: definitions["v1ExpireApiKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ExpireApiKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_DeleteApiKey: {
    parameters: {
      path: {
        prefix: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1DeleteApiKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_DebugCreateNode: {
    parameters: {
      body: {
        body: definitions["v1DebugCreateNodeRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1DebugCreateNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_Health: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1HealthResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ListNodes: {
    parameters: {
      query: {
        user?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ListNodesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_BackfillNodeIPs: {
    parameters: {
      query: {
        confirmed?: boolean;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1BackfillNodeIPsResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_RegisterNode: {
    parameters: {
      query: {
        user?: string;
        key?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1RegisterNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_GetNode: {
    parameters: {
      path: {
        nodeId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_DeleteNode: {
    parameters: {
      path: {
        nodeId: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1DeleteNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_SetApprovedRoutes: {
    parameters: {
      path: {
        nodeId: string;
      };
      body: {
        body: definitions["HeadscaleServiceSetApprovedRoutesBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1SetApprovedRoutesResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ExpireNode: {
    parameters: {
      path: {
        nodeId: string;
      };
      query: {
        expiry?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ExpireNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_RenameNode: {
    parameters: {
      path: {
        nodeId: string;
        newName: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1RenameNodeResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_SetTags: {
    parameters: {
      path: {
        nodeId: string;
      };
      body: {
        body: definitions["HeadscaleServiceSetTagsBody"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1SetTagsResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_GetPolicy: {
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1GetPolicyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_SetPolicy: {
    parameters: {
      body: {
        body: definitions["v1SetPolicyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1SetPolicyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ListPreAuthKeys: {
    parameters: {
      query: {
        user?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ListPreAuthKeysResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_CreatePreAuthKey: {
    parameters: {
      body: {
        body: definitions["v1CreatePreAuthKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1CreatePreAuthKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_DeletePreAuthKey: {
    parameters: {
      query: {
        user?: string;
        key?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1DeletePreAuthKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ExpirePreAuthKey: {
    parameters: {
      body: {
        body: definitions["v1ExpirePreAuthKeyRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ExpirePreAuthKeyResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_ListUsers: {
    parameters: {
      query: {
        id?: string;
        name?: string;
        email?: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1ListUsersResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_CreateUser: {
    parameters: {
      body: {
        body: definitions["v1CreateUserRequest"];
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1CreateUserResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_DeleteUser: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1DeleteUserResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
  HeadscaleService_RenameUser: {
    parameters: {
      path: {
        oldId: string;
        newName: string;
      };
    };
    responses: {
      /** A successful response. */
      200: {
        schema: definitions["v1RenameUserResponse"];
      };
      /** An unexpected error response. */
      default: {
        schema: definitions["rpcStatus"];
      };
    };
  };
}

export interface external {}
